#!/bin/sh

cd /data/iptables

source script/initialize
source script/ping

MANGOS="mangos-realm mangos-world-000 mangos-world-243 mangos-world-303"
SUNUO="ultima-online uo-world"
# IN  - Server    => Exterieur
# OUT - Exterieur => Server

INTERFACE=lo
source script/open

INTERFACE=eth0
TCP_IN=" ssh domain rndc ntp rsync whois http https smtp                       razor razor-ping ftp ftp-data        svn git"
TCP_OUT="ssh domain rndc     rsync       http https smtp submission imap imaps       razor-ping ftp ftp-data murmur svn     $MANGOS $SUNUO"
UDP_IN=" domain          openvpn dcc murmur svn git"
UDP_OUT="domain rndc ntp openvpn dcc murmur svn"
WHITELIST=""
BLACKLIST="87.164.98.181 89.55.28.219"
source script/bandwidth
source script/filter_ip
source script/filter_port

# Server OpenVPN sygil.org (Probablement inutile
INTERFACE=tap0
source script/open

# Client OpenVPN sygil.org
INTERFACE=tap1
TCP_IN=" microsoft-ds netbios-ssn http https             ssh snmp"
TCP_OUT="microsoft-ds netbios-ssn http https webmin ntop ssh      domain rndc mysql gkrellmd"
UDP_IN=" netbios-ns netbios-dgm domain rndc snmp ping"
UDP_OUT="netbios-ns netbios-dgm domain rndc"
source script/filter_ip
source script/filter_port

# Client OpenVPN gageiatx.org
INTERFACE=tap2
TCP_IN="microsoft-ds netbios-ssn"
TCP_OUT="microsoft-ds netbios-ssn"
UDP_IN="netbios-ns netbios-dgm"
UDP_OUT="netbios-ns netbios-dgm"
source script/filter_port
source script/postrouting



source script/cleanup
source script/save

 
