#!/bin/sh
# Copyright 2008-2009 Sygil.org
# Distributed under the terms of the GNU General Public License v2
# $Header$

cd /data/iptables
IPTABLES="/sbin/iptables"

source script/color
source script/initialize
source script/ping

# Alias
# pour specifier une plage de port ou un groupe de port 
# lier a un logiciel specifique

#exemple="27015:27020"

# OUT - Server    => ??
# IN  - ??        => Server

INTERFACE=lo
source script/open

INTERFACE=eth0

# ajout des alias de la maniere suivante:
# TCP_OUT="$exemple"
TCP_OUT="ssh domain rndc rsync whois http https smtp                       ftp ftp-data svn git"
TCP_IN=" ssh domain rndc rsync       http https smtp submission imap imaps ftp ftp-data svn git"

UDP_OUT="domain      svn git"
UDP_IN=" domain rndc svn git"

FORWARD=0
WHITELIST=""
# Server ayant effectuer une attaque
BLACKLIST="87.164.98.181 89.55.28.219"

source script/bandwidth
source script/filter_ip
source script/filter_port

# Si vous avez plusieurs carte reseau ou un Client OpenVPN 
# specifier l'interface (voir ifconfig)

INTERFACE=eth1
TCP_OUT="microsoft-ds netbios-ssn http https             ssh snmp"
TCP_IN=" microsoft-ds netbios-ssn http https webmin ntop ssh      domain rndc mysql gkrellmd"
UDP_OUT="netbios-ns netbios-dgm domain rndc snmp ping"
UDP_IN=" netbios-ns netbios-dgm domain rndc"
FORWARD=0
source script/filter_port
source script/postrouting


source script/cleanup
source script/save

 
