#!/bin/sh

##
# Description: Executable et fichier de config
#
# Author: Mathieu Chocat <mathieu@chocat.com> / Ashaan
# Contributor: none
#
# Revision: $REVISION$
#
# Copyright(c) 2008-2009 Mathieu Chocat (or Sygil.org if applicable)
# Distributed under the terms of the GNU General Public License v2
##

echo -e "$CBLUE>$CBASE Add Bandwidth log on $CRED$INTERFACE$Cbase"
$IPTABLES -A INPUT   --in-interface  $INTERFACE --jump LOG --log-level 7 --log-prefix BANDWIDTH_IN:
$IPTABLES -A FORWARD --out-interface $INTERFACE --jump LOG --log-level 7 --log-prefix BANDWIDTH_OUT:
$IPTABLES -A FORWARD --in-interface  $INTERFACE --jump LOG --log-level 7 --log-prefix BANDWIDTH_IN:
$IPTABLES -A OUTPUT  --out-interface $INTERFACE --jump LOG --log-level 7 --log-prefix BANDWIDTH_OUT:

