#!/bin/sh

##
# Description: Executable et fichier de config
#
# Author: Mathieu Chocat <mathieu@chocat.com> / Ashaan
# Contributor: none
#
# Revision: $REVISION$
#
# Copyright(c) 2008-2009 Mathieu Chocat (or Sygil.org if applicable)
# Distributed under the terms of the GNU General Public License v2
##

# VARIABLES
IPTABLES="/sbin/iptables"

# Color
Cbase='\e[0m'
CBASE='\e[0m\e[1m'
Cblue='\e[0;34m'
CBLUE='\e[1;34m'
Cred='\e[0;31m'
CRED='\e[1;31m'
Cgreen='\e[0;32m'
CGREEN='\e[1;32m'

