#!/bin/sh

##
# Description: Executable et fichier de config
#
# Author: Mathieu Chocat <mathieu@chocat.com> / Ashaan
# Contributor: none
#
# Revision: $REVISION$
#
# Copyright(c) 2008-2009 Mathieu Chocat (or Sygil.org if applicable)
# Distributed under the terms of the GNU General Public License v2
##

if [ "$RWHITELIST" != "" ];
then
    echo -e "$CBLUE>$CBASE Accept All from:$Cbase"

    TEMP=""
    for WHITE in $RWHITELIST;
    do
        if [ "$TEMP" != "" ]; then TEMP="$TEMP, "; fi
        TEMP="$TEMP$Cgreen$WHITE$Cbase"
        $IPTABLES --append INPUT   -m iprange --src-range $WHITE --jump ACCEPT
        $IPTABLES --append OUTPUT  -m iprange --dst-range $WHITE --jump ACCEPT
        $IPTABLES --append FORWARD -m iprange --dst-range $WHITE --jump ACCEPT
        $IPTABLES --append FORWARD -m iprange --src-range $WHITE --jump ACCEPT
    done;
    echo -e "$CRED<$Cbase $TEMP"
fi;

if [ "$RBLACKLIST" != "" ];
then
    echo -e "$CBLUE>$CBASE Reject All from:$Cbase"

    TEMP=""
    for BLACK in $RBLACKLIST;
    do
        if [ "$TEMP" != "" ]; then TEMP="$TEMP, "; fi
        TEMP="$TEMP$Cgreen$BLACK$Cbase"
        $IPTABLES --append INPUT   -m iprange --src-range $BLACK --jump DROP
        $IPTABLES --append OUTPUT  -m iprange --dst-range $BLACK --jump DROP
        $IPTABLES --append FORWARD -m iprange --dst-range $BLACK --jump DROP
	$IPTABLES --append FORWARD -m iprange --src-range $BLACK --jump DROP
done;
    echo -e "$CRED<$Cbase $TEMP"
fi;
