#!/bin/sh
# Copyright 2008-2009 Sygil.org
# Distributed under the terms of the GNU General Public License v2
# $Header$

if [ "$WHITELIST" != "" ];
then
    echo -e "$CBLUE>$CBASE Accept All on $CRED$INTERFACE$CBASE from:$Cbase"

    TEMP=""
    for WHITE in $WHITELIST;
    do
        if [ "$TEMP" != "" ]; then TEMP="$TEMP, "; fi
        TEMP="$TEMP$Cgreen$WHITE$Cbase"
        $IPTABLES --append INPUT  --in-interface  $INTERFACE --source      $WHITE --jump ACCEPT
        $IPTABLES --append OUTPUT --out-interface $INTERFACE --destination $WHITE --jump ACCEPT
    done;
    echo -e "$CRED<$Cbase $TEMP"
fi;

if [ "$BLACKLIST" != "" ];
then
    echo -e "$CBLUE>$CBASE Reject All on $CRED$INTERFACE$CBASE from: $Cbase"

    TEMP=""
    for BLACK in $BLACKLIST;
    do
        if [ "$TEMP" != "" ]; then TEMP="$TEMP, "; fi
        TEMP="$TEMP$Cgreen$BLACK$Cbase"
        $IPTABLES --append INPUT  --in-interface  $INTERFACE --source      $BLACK --jump DROP
        $IPTABLES --append OUTPUT --out-interface $INTERFACE --destination $BLACK --jump DROP
    done;
    echo -e "$CRED<$Cbase $TEMP"
fi;
