#!/bin/sh

##
# Description: Executable et fichier de config
#
# Author: Mathieu Chocat <mathieu@chocat.com> / Ashaan
# Contributor: none
#
# Revision: $REVISION$
#
# Copyright(c) 2008-2009 Mathieu Chocat (or Sygil.org if applicable)
# Distributed under the terms of the GNU General Public License v2
##

if [ "$WHITELIST" != "" ];
then
    echo -e "$CBLUE>$CBASE Accept All on $CRED$CBASE from:$Cbase"

    TEMP=""
    for WHITE in $WHITELIST;
    do
        if [ "$TEMP" != "" ]; then TEMP="$TEMP, "; fi
        TEMP="$TEMP$Cgreen$WHITE$Cbase"
        $IPTABLES --append INPUT   --source      $WHITE --jump ACCEPT
        $IPTABLES --append OUTPUT  --destination $WHITE --jump ACCEPT
	$IPTABLES --append FORWARD --source      $WHITE --jump ACCEPT
        $IPTABLES --append FORWARD --destination $WHITE --jump ACCEPT

    done;
    echo -e "$CRED<$Cbase $TEMP"
fi;

if [ "$BLACKLIST" != "" ];
then
    echo -e "$CBLUE>$CBASE Reject All on $CRED$CBASE from: $Cbase"

    TEMP=""
    for BLACK in $BLACKLIST;
    do
        if [ "$TEMP" != "" ]; then TEMP="$TEMP, "; fi
        TEMP="$TEMP$Cgreen$BLACK$Cbase"
        $IPTABLES --append INPUT   --source      $BLACK --jump DROP
        $IPTABLES --append OUTPUT  --destination $BLACK --jump DROP
        $IPTABLES --append FORWARD --source      $BLACK --jump DROP
        $IPTABLES --append FORWARD --destination $BLACK --jump DROP
	done;
    echo -e "$CRED<$Cbase $TEMP"
fi;
