#!/bin/sh
# Copyright 2008-2009 Sygil.org
# Distributed under the terms of the GNU General Public License v2
# $Header$

 
# Forward
echo 1 > /proc/sys/net/ipv4/ip_forward

echo -e "$CBLUE>$CBASE Reset Iptables$Cbase"
$IPTABLES -F
$IPTABLES -F -t nat
$IPTABLES -X

echo -e "$CBLUE>$CBASE Reject All By Default$Cbase"
$IPTABLES -P INPUT   DROP
$IPTABLES -P OUTPUT  DROP
$IPTABLES -P FORWARD DROP

echo -e "$CBLUE>$CBASE Accepte Established connection$Cbase"
$IPTABLES -A INPUT  --protocol icmp -m state --state ESTABLISHED,RELATED -j ACCEPT
$IPTABLES -A INPUT  --protocol tcp  -m state --state ESTABLISHED,RELATED -j ACCEPT
$IPTABLES -A INPUT  --protocol udp  -m state --state ESTABLISHED,RELATED -j ACCEPT
$IPTABLES -A OUTPUT --protocol icmp -m state --state ESTABLISHED,RELATED -j ACCEPT
$IPTABLES -A OUTPUT --protocol tcp  -m state --state ESTABLISHED,RELATED -j ACCEPT
$IPTABLES -A OUTPUT --protocol udp  -m state --state ESTABLISHED,RELATED -j ACCEPT


