#!/bin/sh

##
# Description: Executable et fichier de config
#
# Author: Mathieu Chocat <mathieu@chocat.com> / Ashaan
# Contributor: none
#
# Revision: $REVISION$
#
# Copyright(c) 2008-2009 Mathieu Chocat (or Sygil.org if applicable)
# Distributed under the terms of the GNU General Public License v2
##

echo -e "$CBLUE>$CBASE Accepte all on $CRED$INTERFACE$Cbase"
$IPTABLES -A INPUT  --in-interface  $INTERFACE -j ACCEPT
$IPTABLES -A OUTPUT --out-interface $INTERFACE -j ACCEPT
if [ $FORWARD = 1 ]; then
    $IPTABLES -A FORWARD --in-interface $INTERFACE -j ACCEPT
    $IPTABLES -A FORWARD --out-interface $INTERFACE -j ACCEPT
    echo -e "$CRED<+$Cbase FORWARD"
fi

