#!/bin/sh
# Copyright 2008-2009 Sygil.org
# Distributed under the terms of the GNU General Public License v2
# $Header$

echo -e "$CBLUE>$CBASE Accepte all on $CRED$INTERFACE$Cbase"
$IPTABLES -A INPUT  --in-interface  $INTERFACE -j ACCEPT
$IPTABLES -A OUTPUT --out-interface $INTERFACE -j ACCEPT

