#!/bin/sh
# Copyright 2008-2009 Sygil.org
# Distributed under the terms of the GNU General Public License v2
# $Header$

echo -e "$CBLUE>$CBASE Accept ICMP PING$Cbase"
$IPTABLES -A INPUT  -p icmp -j ACCEPT
$IPTABLES -A OUTPUT -p icmp -j ACCEPT

