#!/bin/sh

##
# Description: Executable et fichier de config
#
# Author: Mathieu Chocat <mathieu@chocat.com> / Ashaan
# Contributor: none
#
# Revision: $REVISION$
#
# Copyright(c) 2008-2009 Mathieu Chocat (or Sygil.org if applicable)
# Distributed under the terms of the GNU General Public License v2
##

echo -e "$CBLUE>$CBASE Enable PostRouting on $CRED$INTERFACE$CBASE$Cbase"
$IPTABLES -t nat -A POSTROUTING -o $INTERFACE -j MASQUERADE

