#!/bin/sh
# Copyright 2008-2009 Sygil.org
# Distributed under the terms of the GNU General Public License v2
# $Header$

echo -e "$CBASE>$CRED Save Rule and Start/restart Iptables (for Gentoo)$Cbase";
/etc/init.d/iptables save
/etc/init.d/iptables restart
